version: "3.8"  
services:  
  vaultwarden:  
    image: vaultwarden/server:latest  
    container_name: vaultwarden  
    restart: always  
    environment:  
     #- LOG_LEVEL=debug
     #- SIGNUPS_ALLOWED=false
      - ADMIN_TOKEN=Any_strong_password
    labels:
      
      - traefik.enable=true
      - traefik.http.middlewares.vaultwarden-websecure-redirect.redirectscheme.scheme=https 
      - traefik.http.routers.vaultwarden-secure.entrypoints=https 
      - traefik.http.routers.vaultwarden-secure.rule=Host(`yourdomain.tld`) 
      - traefik.http.routers.vaultwarden-secure.service=vaultwarden
      - traefik.http.routers.vaultwarden-secure.tls=true 
      - traefik.http.routers.vaultwarden-secure.tls.certresolver=default 
      - traefik.http.routers.vaultwarden.entrypoints=http 
      - traefik.http.routers.vaultwarden.middlewares=vaultwarden-websecure-redirect@docker
      - traefik.http.routers.vaultwarden.rule=Host(`yourdomain.tld`) 
      - traefik.http.services.vaultwarden.loadbalancer.server.port=80

#----------------
  #    - traefik.enable=true
  #    - traefik.http.routers.vaultwarden.rule=Host(`yourdomain.tld`)
  #    - traefik.http.routers.vaultwarden.tls=true
  #    - traefik.http.routers.vaultwarden.entrypoints=http,https
  #    - traefik.http.routers.vaultwarden.tls.certresolver=default
  #    - traefik.http.middlewares.vaultwarden.headers.SSLRedirect=true
  #    - traefik.http.middlewares.vaultwarden.headers.STSSeconds=315360000
  #    - traefik.http.middlewares.vaultwarden.headers.browserXSSFilter=true
  #    - traefik.http.middlewares.vaultwarden.headers.contentTypeNosniff=true
  #    - traefik.http.middlewares.vaultwarden.headers.forceSTSHeader=true
  #    - traefik.http.middlewares.vaultwarden.headers.SSLHost=traefikdomain.tld
  #    - traefik.http.middlewares.vaultwarden.headers.STSIncludeSubdomains=true
  #    - traefik.http.middlewares.vaultwarden.headers.STSPreload=true
  #    - traefik.http.routers.vaultwarden.middlewares=vaultwarden@docker
  #    - traefik.http.services.vaultwarden.loadbalancer.server.port=80
  #------------------    

    networks:
      - your_traefik_network
      - default
    volumes:  
      - ./vaultdata/:/data  

networks:
  your_traefik_network :
    external: true